// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxKOANIcwWhU4VaZTeu5cdDwVRzoebJF0',
    appId: '1:686857392136:web:c92522663fa6f9ca8641bd',
    messagingSenderId: '686857392136',
    projectId: 'bookey-6618c',
    authDomain: 'bookey-6618c.firebaseapp.com',
    storageBucket: 'bookey-6618c.firebasestorage.app',
    measurementId: 'G-MHE335MFDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxKOANIcwWhU4VaZTeu5cdDwVRzoebJF0',
    appId: '1:686857392136:android:c92522663fa6f9ca8641bd',
    messagingSenderId: '686857392136',
    projectId: 'bookey-6618c',
    storageBucket: 'bookey-6618c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxKOANIcwWhU4VaZTeu5cdDwVRzoebJF0',
    appId: '1:686857392136:ios:c92522663fa6f9ca8641bd',
    messagingSenderId: '686857392136',
    projectId: 'bookey-6618c',
    storageBucket: 'bookey-6618c.firebasestorage.app',
    iosBundleId: 'com.example.bookeyFlutter',
  );
}
